\c games_dev;

INSERT INTO games (name, image, cost, genre, game_description, release_date, multiplayer) VALUES
('League of League of Legends', 'https://wallpaperaccess.com/full/2379005.jpg', 0.00, 'Multiplayer Online Battle Arena (MOBA)', 'League of Legends is a team-based strategy game where two teams of five powerful champions face off to destroy the base of opposing team. Choose from over 140 champions to make epic plays, secure kills, and take down towers as you battle your way to victory.', 2009, true), 
('Valorant', 'https://stanforddaily.com/wp-content/uploads/2020/08/image-2.png', 0.00, 'First-person shooter', 'Valorant is a team-based first-person tactical hero shooter set in the near future. Players play as one of a set of Agents, characters based on several countries and cultures around the world. In the main game mode, players are assigned to either the attacking or defending team with each team having five players on it.', 2020, true), 
('Fortnite', 'https://cdn.marvel.com/content/1x/donut_lob_crd_01.jpg', 0.00, 'Multiplayer Battle Royale', 'Grab all of your friends and drop into Fortnite, a massive 100-player face-off that combines looting, crafting, shootouts and chaos. The result is a completely unpredictable competitive online experience that gets bigger and even wilder with every new season.', 2017, true), 
('Metal Gear Solid 3: Snake Eater', 'https://upload.wikimedia.org/wikipedia/en/b/b3/Mgs3box.jpg', 14.99, 'Action-Adventure', 'Use camouflage wisely to survive deep in hostile territory. Infiltrate and survive by paying attention to your hunting skills and instincts. Use the interactive environments to your advantage -- creating traps to catch enemies and prey. Features a blockbuster musical score composed by Harry Gregson-Williams', 2004, false),
('Call Of Duty Black Ops 3', 'https://assets1.ignimgs.com/2015/09/01/callofdutyblackops3-buttonjpg-03c985.jpg?width=300&crop=1%3A1%2Csmart', 59.99, 'First-Person Shooter', 'Call of Duty: Black Ops III combines three unique game modes: Campaign, Multiplayer and Zombies, providing fans with the deepest and most ambitious Call of Duty ever. The Campaign has been designed as a co-op game that can be played with up to four players online, or as a solo cinematic thrill-ride. Multiplayer will be the most rewarding and most engaging to date, with new ways to rank up, customise, and gear up for battle. Zombies delivers an all-new mind-blowing experience with its own dedicated narrative.', 2015, true),
('New Super Mario Bros', 'https://musescore.com/static/musescore/scoredata/g/3de02113bffaaa8bf0bba1b4ab9e6637da9ff17f/score_0.svg?no-cache=1658749041', 39.99, 'Platformer Action-Adventure', 'Boasting incredible 3D graphics to accompany classic 2D gameplay, this fast-paced adventure will have Mario fans cheering. New Super Mario Bros. features eight all-new worlds, each filled with extra levels, hidden paths, and secrets galore. It is possible to complete the game without visiting every world, which means you have to track down many alternate exits to visit every nook and cranny in the game. Run, jump, and stomp your way through raging volcanoes, tropical islands, snowcapped peaks, and unimaginable challenges!', 2006, true), 
('ULTIMATE MARVEL VS. CAPCOM 3', 'https://img.opencritic.com/game/3696/l5CgvCWl.jpg', 24.99, 'Fighting', 'Marvel and Capcom join forces to deliver the most frenetic 3 vs. 3 tag battles ever with Ultimate Marvel vs. Capcom 3. This release comes fully loaded, including all previous DLC, and the Marvel vs. Capcom: Official Complete Works. Select some of the most iconic Marvel and Capcom characters, and customize your team with "Heroes and Heralds" mode. Once you hone your skills, hop online and go head-to-head against players from around the world to see who is the strongest in the universe.', 2011, true), 
('Super Smash Bros. Brawl', 'https://images5.alphacoders.com/739/739695.jpg', 59.99, 'Fighting Platform', 'Engage the rage with Super Smash Bros. Brawl! The third instalment of the incredibly successful Super Smash Bros. series. The roster is longer than ever, but that just means more butt to kick across over a dozen different, graphic-rich stages with original moves, new modified moves, and a brand-new super attack called Final Smash! With a variety of new modes, an absolutely epic soundtrack and the ability to play with distant friends through online multiplayer, this is a game you have to break your own fingers to put down. See your favourite Smash Bros. character, redesigned from their most recent games, brawl onto your screen once again!', 2008, true), 
('The Legend of Zelda: The Wind Waker HD', 'https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/wiiu_14/SI_WiiU_TheLegendofZeldaTheWindWakerHD_image1600w.jpg', 89.99, 'Action-Adventure RPG', 'Developed and published by Nintendo, it is a remastered version of the 2002 GameCube game, The Legend of Zelda: The Wind Waker. The Wind Waker HD expands on the original by introducing native 1080p resolution, an alternate lighting engine, as well as new gameplay features and modifications. The release of the game marked the ten-year anniversary of the international release of the original, and was the first game in the Zelda series released on the Wii U.', 2013, false);